### ISSUE TITLE
How to fix errors in code ex1_burgers_eval.ipynb: NameError: name 'FourierTransformer' is not defined

### ISSUE THREAD

**Issue by PKUHaoWang** [scaomath/galerkin-transformer#9]
How to fix errors in code ex1_burgers_eval.ipynb:
NameError: name 'FourierTransformer' is not defined

**Comment by scaomath** [comment]
Hi @WH0226 have you been able to resolve this locally?

**Comment by PKUHaoWang** [comment]
Yes, thank you!
